In [2]:
import Datos, EstrategiaParticionado, Clasificador

dataPath = './ConjuntosDatosIntroFAA/'

dataset1 = Datos.Datos(dataPath + "german.csv")
print(dataset1.datos)

dataset2 = Datos.Datos(dataPath + 'tic-tac-toe.csv')
print(dataset2.datos)

estrategia = EstrategiaParticionado.ValidacionCruzada(0.1)
print("Repeticiones:", estrategia.repetitions)
print("Tamano de la prueba:", estrategia.test_size)
for partition in estrategia.creaParticiones(dataset1.datos):
    print("TRAIN")
    print(partition.indicesTrain)
    print("TEST")
    print(partition.indicesTest)
estrategiaS = EstrategiaParticionado.ValidacionSimple(10, 0.2)
print("Repeticiones:", estrategiaS.repetitions)
print("Tamano de la prueba:", estrategiaS.test_size)
partition = estrategiaS.creaParticiones(dataset1.datos)
print("TRAIN")
print(partition.indicesTrain)
print("TEST")
print(partition.indicesTest)


[[ 1  6  5 ...  2  1  1]
 [ 2 48  3 ...  1  1  2]
 [ 4 12  5 ...  1  1  1]
 ...
 [ 4 12  3 ...  1  1  1]
 [ 1 45  3 ...  2  1  2]
 [ 2 45  5 ...  1  1  1]]
[[3 3 3 ... 2 2 2]
 [3 3 3 ... 3 2 2]
 [3 3 3 ... 2 3 2]
 ...
 [2 3 2 ... 2 3 1]
 [2 3 2 ... 2 3 1]
 [2 2 3 ... 3 3 1]]
Repeticiones: 9
Tamano de la prueba: 0.1
TRAIN
[404, 395, 741, 219, 935, 907, 960, 958, 2, 59, 920, 823, 336, 114, 895, 444, 248, 539, 840, 295, 991, 513, 42, 792, 467, 171, 658, 614, 457, 91, 990, 592, 928, 289, 915, 666, 687, 549, 115, 391, 187, 40, 976, 520, 477, 56, 482, 659, 341, 386, 296, 498, 891, 94, 389, 931, 180, 527, 157, 158, 595, 13, 819, 241, 237, 364, 888, 408, 508, 278, 402, 906, 817, 50, 338, 963, 812, 611, 510, 221, 127, 919, 864, 685, 32, 714, 657, 81, 982, 753, 304, 742, 887, 686, 422, 721, 546, 987, 572, 808, 623, 280, 435, 857, 362, 392, 113, 100, 978, 436, 889, 577, 516, 620, 588, 202, 174, 349, 908, 672, 552, 670, 617, 359, 501, 121, 453, 259, 979, 589, 170, 612, 677, 130, 830, 5, 583, 835, 